// Code generated by go run ./internal/operations/genenums; DO NOT EDIT.

package operations

import "fencer/cli/api/schema"

var (
	vulnerabilityOrderBy = []schema.VulnerabilitiesListParamsOrderBy{
		schema.VulnerabilitiesListParamsOrderByAssetName,
		schema.VulnerabilitiesListParamsOrderByAssignee,
		schema.VulnerabilitiesListParamsOrderByAssigneeName,
		schema.VulnerabilitiesListParamsOrderByCategory,
		schema.VulnerabilitiesListParamsOrderByFirstSeen,
		schema.VulnerabilitiesListParamsOrderById,
		schema.VulnerabilitiesListParamsOrderByMinusAssetName,
		schema.VulnerabilitiesListParamsOrderByMinusAssignee,
		schema.VulnerabilitiesListParamsOrderByMinusAssigneeName,
		schema.VulnerabilitiesListParamsOrderByMinusCategory,
		schema.VulnerabilitiesListParamsOrderByMinusFirstSeen,
		schema.VulnerabilitiesListParamsOrderByMinusId,
		schema.VulnerabilitiesListParamsOrderByMinusPriorityLevel,
		schema.VulnerabilitiesListParamsOrderByMinusSeverity,
		schema.VulnerabilitiesListParamsOrderByMinusSlaDeadline,
		schema.VulnerabilitiesListParamsOrderByMinusStatus,
		schema.VulnerabilitiesListParamsOrderByMinusTitle,
		schema.VulnerabilitiesListParamsOrderByPriorityLevel,
		schema.VulnerabilitiesListParamsOrderBySeverity,
		schema.VulnerabilitiesListParamsOrderBySlaDeadline,
		schema.VulnerabilitiesListParamsOrderByStatus,
		schema.VulnerabilitiesListParamsOrderByTitle,
	}
	detectionOrderBy = []schema.DetectionsListParamsOrderBy{
		schema.DetectionsListParamsOrderByAsset,
		schema.DetectionsListParamsOrderByAssetName,
		schema.DetectionsListParamsOrderByAssigneeName,
		schema.DetectionsListParamsOrderByConfidenceLabel,
		schema.DetectionsListParamsOrderByDetectedAt,
		schema.DetectionsListParamsOrderByMinusAsset,
		schema.DetectionsListParamsOrderByMinusAssetName,
		schema.DetectionsListParamsOrderByMinusAssigneeName,
		schema.DetectionsListParamsOrderByMinusConfidenceLabel,
		schema.DetectionsListParamsOrderByMinusDetectedAt,
		schema.DetectionsListParamsOrderByMinusSeverity,
		schema.DetectionsListParamsOrderByMinusStatus,
		schema.DetectionsListParamsOrderByMinusTitle,
		schema.DetectionsListParamsOrderBySeverity,
		schema.DetectionsListParamsOrderByStatus,
		schema.DetectionsListParamsOrderByTitle,
	}
	assetOrderBy = []schema.AssetInventoryListParamsOrderBy{
		schema.AssetInventoryListParamsOrderByBelongsTo,
		schema.AssetInventoryListParamsOrderByDescription,
		schema.AssetInventoryListParamsOrderByKind,
		schema.AssetInventoryListParamsOrderByMinusBelongsTo,
		schema.AssetInventoryListParamsOrderByMinusDescription,
		schema.AssetInventoryListParamsOrderByMinusKind,
		schema.AssetInventoryListParamsOrderByMinusProvider,
		schema.AssetInventoryListParamsOrderByMinusRegion,
		schema.AssetInventoryListParamsOrderByProvider,
		schema.AssetInventoryListParamsOrderByRegion,
	}
	identityOrderBy = []schema.IdentitiesListParamsOrderBy{
		schema.IdentitiesListParamsOrderByDisplayName,
		schema.IdentitiesListParamsOrderByFirstSeenAt,
		schema.IdentitiesListParamsOrderByIdentityRelationshipDisplay,
		schema.IdentitiesListParamsOrderByIdentityStatusDisplay,
		schema.IdentitiesListParamsOrderByIdentityTypeDisplay,
		schema.IdentitiesListParamsOrderByLastSeenAt,
		schema.IdentitiesListParamsOrderByMinusDisplayName,
		schema.IdentitiesListParamsOrderByMinusFirstSeenAt,
		schema.IdentitiesListParamsOrderByMinusIdentityRelationshipDisplay,
		schema.IdentitiesListParamsOrderByMinusIdentityStatusDisplay,
		schema.IdentitiesListParamsOrderByMinusIdentityTypeDisplay,
		schema.IdentitiesListParamsOrderByMinusLastSeenAt,
		schema.IdentitiesListParamsOrderByMinusNeedsReview,
		schema.IdentitiesListParamsOrderByMinusPrimaryEmail,
		schema.IdentitiesListParamsOrderByNeedsReview,
		schema.IdentitiesListParamsOrderByPrimaryEmail,
	}
	scanVulnerabilityOrderBy = []schema.ScanVulnerabilitySnapshotsListParamsOrderBy{
		schema.ScanVulnerabilitySnapshotsListParamsOrderByAssetName,
		schema.ScanVulnerabilitySnapshotsListParamsOrderByCategory,
		schema.ScanVulnerabilitySnapshotsListParamsOrderByFirstSeen,
		schema.ScanVulnerabilitySnapshotsListParamsOrderByMinusAssetName,
		schema.ScanVulnerabilitySnapshotsListParamsOrderByMinusCategory,
		schema.ScanVulnerabilitySnapshotsListParamsOrderByMinusFirstSeen,
		schema.ScanVulnerabilitySnapshotsListParamsOrderByMinusSeverity,
		schema.ScanVulnerabilitySnapshotsListParamsOrderByMinusTitle,
		schema.ScanVulnerabilitySnapshotsListParamsOrderBySeverity,
		schema.ScanVulnerabilitySnapshotsListParamsOrderByTitle,
	}
	ignoreReasons = []schema.IgnoredReasonEnum{
		schema.IgnoredReasonEnumAcceptableRisk,
		schema.IgnoredReasonEnumDuplicate,
		schema.IgnoredReasonEnumFalsePositive,
		schema.IgnoredReasonEnumNoFixAvailable,
		schema.IgnoredReasonEnumRuleDisabled,
		schema.IgnoredReasonEnumSuperseded,
		schema.IgnoredReasonEnumThirdPartyCode,
		schema.IgnoredReasonEnumWillNotFix,
	}
	deferDays = []schema.DeferDaysEnum{
		schema.N14,
		schema.N30,
		schema.N7,
		schema.N90,
	}
	priorityLevels = []schema.PriorityLevelEnum{
		schema.PriorityLevelEnumHigh,
		schema.PriorityLevelEnumLow,
		schema.PriorityLevelEnumMinimal,
		schema.PriorityLevelEnumModerate,
		schema.PriorityLevelEnumUrgent,
	}
	vulnerabilityCategory = []schema.VulnerabilitiesListParamsCategory{
		schema.VulnerabilitiesListParamsCategoryAiAgent,
		schema.VulnerabilitiesListParamsCategoryApplication,
		schema.VulnerabilitiesListParamsCategoryArtifact,
		schema.VulnerabilitiesListParamsCategoryCode,
		schema.VulnerabilitiesListParamsCategoryConfig,
		schema.VulnerabilitiesListParamsCategoryDependency,
		schema.VulnerabilitiesListParamsCategoryEndpoint,
		schema.VulnerabilitiesListParamsCategoryInfrastructure,
		schema.VulnerabilitiesListParamsCategoryLicense,
		schema.VulnerabilitiesListParamsCategoryLogs,
		schema.VulnerabilitiesListParamsCategoryNetwork,
		schema.VulnerabilitiesListParamsCategorySecret,
	}
	scanVulnerabilityCategory = []schema.ScanVulnerabilitySnapshotsListParamsCategory{
		schema.ScanVulnerabilitySnapshotsListParamsCategoryAiAgent,
		schema.ScanVulnerabilitySnapshotsListParamsCategoryApplication,
		schema.ScanVulnerabilitySnapshotsListParamsCategoryArtifact,
		schema.ScanVulnerabilitySnapshotsListParamsCategoryCode,
		schema.ScanVulnerabilitySnapshotsListParamsCategoryConfig,
		schema.ScanVulnerabilitySnapshotsListParamsCategoryDependency,
		schema.ScanVulnerabilitySnapshotsListParamsCategoryEndpoint,
		schema.ScanVulnerabilitySnapshotsListParamsCategoryInfrastructure,
		schema.ScanVulnerabilitySnapshotsListParamsCategoryLicense,
		schema.ScanVulnerabilitySnapshotsListParamsCategoryLogs,
		schema.ScanVulnerabilitySnapshotsListParamsCategoryNetwork,
		schema.ScanVulnerabilitySnapshotsListParamsCategorySecret,
	}
)
