package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type enumSpec struct {
	Type string
	Var  string
}

var enums = []enumSpec{
	{Type: "VulnerabilitiesListParamsOrderBy", Var: "vulnerabilityOrderBy"},
	{Type: "DetectionsListParamsOrderBy", Var: "detectionOrderBy"},
	{Type: "AssetInventoryListParamsOrderBy", Var: "assetOrderBy"},
	{Type: "IdentitiesListParamsOrderBy", Var: "identityOrderBy"},
	{Type: "ScanVulnerabilitySnapshotsListParamsOrderBy", Var: "scanVulnerabilityOrderBy"},
	{Type: "IgnoredReasonEnum", Var: "ignoreReasons"},
	{Type: "DeferDaysEnum", Var: "deferDays"},
	{Type: "PriorityLevelEnum", Var: "priorityLevels"},
	{Type: "VulnerabilitiesListParamsCategory", Var: "vulnerabilityCategory"},
	{Type: "ScanVulnerabilitySnapshotsListParamsCategory", Var: "scanVulnerabilityCategory"},
}

func main() {
	schemaPath := flagOrDefault(os.Args, "-schema", "api/schema/generated.go")
	outPath := flagOrDefault(os.Args, "-out", "internal/operations/schema_enums_gen.go")

	values, err := extractEnumConsts(schemaPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "genenums: %v\n", err)
		os.Exit(1)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by go run ./internal/operations/genenums; DO NOT EDIT.\n\n")
	buf.WriteString("package operations\n\n")
	buf.WriteString("import \"fencer/cli/api/schema\"\n\n")
	buf.WriteString("var (\n")
	for _, spec := range enums {
		names := values[spec.Type]
		if len(names) == 0 {
			fmt.Fprintf(os.Stderr, "genenums: no constants found for %s\n", spec.Type)
			os.Exit(1)
		}
		fmt.Fprintf(&buf, "\t%s = []schema.%s{\n", spec.Var, spec.Type)
		for _, name := range names {
			fmt.Fprintf(&buf, "\t\tschema.%s,\n", name)
		}
		buf.WriteString("\t}\n")
	}
	buf.WriteString(")\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "genenums: format: %v\n%s\n", err, buf.String())
		os.Exit(1)
	}
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "genenums: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "genenums: %v\n", err)
		os.Exit(1)
	}
}

func flagOrDefault(args []string, name, fallback string) string {
	prefix := name + "="
	for i, arg := range args {
		if arg == name && i+1 < len(args) {
			return args[i+1]
		}
		if strings.HasPrefix(arg, prefix) {
			return strings.TrimPrefix(arg, prefix)
		}
	}
	return fallback
}

func extractEnumConsts(path string) (map[string][]string, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.SkipObjectResolution)
	if err != nil {
		return nil, err
	}
	wanted := make(map[string]struct{}, len(enums))
	for _, spec := range enums {
		wanted[spec.Type] = struct{}{}
	}
	found := make(map[string][]string, len(enums))
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.CONST {
			continue
		}
		currentType := ""
		for _, spec := range gen.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			if name := typeName(valueSpec.Type); name != "" {
				currentType = name
			}
			if _, ok := wanted[currentType]; !ok {
				continue
			}
			for _, ident := range valueSpec.Names {
				found[currentType] = append(found[currentType], ident.Name)
			}
		}
	}
	for typeName, names := range found {
		sort.Strings(names)
		found[typeName] = names
	}
	return found, nil
}

func typeName(expr ast.Expr) string {
	ident, ok := expr.(*ast.Ident)
	if !ok {
		return ""
	}
	return ident.Name
}
